### PR TITLE
Enable apt to do automated security updates

### PR DESCRIPTION
**Pull request by limed**
Sets up automated security package updates on the OS

### CODE REVIEW

**Review by escattone — APPROVED** [review]
@limed This is cool. Before this I had never heard of the `unattended-upgrades` `apt` package. This looks good to me based on the documents I read. We'll at least get daily updates of security-related changes.

I have one question though. With this configuration, I don't think we'll get reports when updates are made, correct? Is there a way to configure this in order to get an email when changes are made?

**Comment by limed** [comment]
> I have one question though. With this configuration, I don't think we'll get reports when updates are made, correct? Is there a way to configure this in order to get an email when changes are made?

Yeah this is possible based on documentation here https://wiki.debian.org/UnattendedUpgrades

> If you plan to use it, you should have some means to monitor your systems, such as installing the apt-listchanges package and configuring it to send you emails about updates

I think you can also configure unattended-upgrades to just send email too:

```
Unattended-Upgrade::Mail "me@example.com";
```

I do have a concern about this though, if we do this we will actually need to have a proper mail setup on the local machine which we can do but its just not setup currently :)

**Comment by bookshelfdave** [comment]
will the instance be automatically rebooted (if required)?

**Comment by limed** [comment]
> will the instance be automatically rebooted (if required)?

No it will not, I do believe there is a setting that allows that though but I've never gone that far when it comes to update. I realize that this probably doesn't fix kernel updates since they need reboots but I figure we can do that one manually :)

**Pull request merged**
